CREATE SCHEMA IF NOT EXISTS ug_base_php DEFAULT CHARACTER SET utf8mb4;

USE ug_base_php;

CREATE TABLE IF NOT EXISTS TBL_USUARIO (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NOMBRE_USUARIO VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  CONTRASENIA VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACTO(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NOMBRES VARCHAR(100),
  EMAIL VARCHAR(150),
  TELEFONO VARCHAR(15),
  MENSAJE VARCHAR(300),
  PRIMARY KEY (ID)
);

/*INSERT*/
INSERT INTO
  TBL_USUARIO (NOMBRE_USUARIO, CONTRASENIA)
VALUES
  ('KGALARZA', '123');

SELECT
  *
FROM
  TBL_USUARIO;